// author wiki link
// book wiki link
// goodreads link
// Isbn
// year


const data = {
    "books": [       
        {
            "id":"1",
            "name":"Frankenstein",
            "author":"Mary Shelley",
            "cover":"f.jpg",
            "epub":"mary-shelley_frankenstein",
            "tags":["scifi"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Mary_Shelley",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Frankenstein",
        },
        {
            "id":"2",
            "name":"At the Earth's Core",
            "author":"Edgar Rice Burroughs",
            "cover":"atec.jpg",
            "epub":"edgar-rice-burroughs_at-the-earths-core",
            "tags":["scifi"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Edgar_Rice_Burroughs",
            "bookWikiLink":"https://en.wikipedia.org/wiki/At_the_Earth%27s_Core_(novel)",
        },
        {
            "id":"3",
            "name":"The Time Machine",
            "author":"H. G. Wells",
            "cover":"ttm.jpg",
            "epub":"h-g-wells_the-time-machine",
            "tags":["scifi"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/H._G._Wells",
            "bookWikiLink":"https://en.wikipedia.org/wiki/The_Time_Machine",
        },
        {
            "id":"4",
            "name":"The War of the Worlds",
            "author":"H. G. Wells",
            "cover":"twotw.jpg",
            "epub":"h-g-wells_the-war-of-the-worlds",
            "tags":["scifi"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/H._G._Wells",
            "bookWikiLink":"https://en.wikipedia.org/wiki/The_War_of_the_Worlds",
        },
        {
            "id":"5",
            "name":"Moby Dick",
            "author":"Herman Melville",
            "cover":"mb.jpg",
            "epub":"herman-melville_moby-dick",
            "tags":["fiction"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Herman_Melville",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Moby-Dick",
        },
        {
            "id":"6",
            "name":"The Strange Case of Dr. Jekyll and Mr. Hyde",
            "author":"Robert Louis Stevenson",
            "cover":"tscodjamh.jpg",
            "epub":"robert-louis-stevenson_the-strange-case-of-dr-jekyll-and-mr-hyde",
            "tags":["scifi", "horror"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Robert_Louis_Stevenson",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Strange_Case_of_Dr_Jekyll_and_Mr_Hyde",
        },
        {
            "id":"7",
            "name":"Journey to the Center of the Earth",
            "author":"Jules Verne",
            "cover":"jttcote.jpg",
            "epub":"jules-verne_journey-to-the-center-of-the-earth_f-a-malleson",
            "tags":["scifi", "adventure"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Jules_Verne",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Journey_to_the_Center_of_the_Earth",
        },
        {
            "id":"8",
            "name":"Siddhartha",
            "author":"Herman Hesse",
            "cover":"s.jpg",
            "epub":"hermann-hesse_siddhartha_gunther-olesch_anke-dreher_amy-coulter_stefan-langer_semyon-chaichenets",
            "tags":["fiction", "spirituality"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Hermann_Hesse",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Siddhartha_(novel)",
        },
        {
            "id":"9",
            "name":"Tao Te Ching",
            "author":"Laozi",
            "cover":"ttc.jpg",
            "epub":"laozi_tao-te-ching_james-legge",
            "tags":["philosophy", "spirituality"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Laozi",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Tao_Te_Ching",
        },
        {
            "id":"10",
            "name":"Dracula",
            "author":"Bram Stoker",
            "cover":"d.jpg",
            "epub":"bram-stoker_dracula",
            "tags":["fiction", "horror"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Bram_Stoker",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Dracula",
        },
        {
            "id":"11",
            "name":"The Murder of Roger Ackroyd",
            "author":"Agatha Christie",
            "cover":"tmora.jpg",
            "epub":"agatha-christie_the-murder-of-roger-ackroyd",
            "tags":["mystery"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Agatha_Christie",
            "bookWikiLink":"https://en.wikipedia.org/wiki/The_Murder_of_Roger_Ackroyd",
        },
        {
            "id":"12",
            "name":"The Murder on the Links",
            "author":"Agatha Christie",
            "cover":"tmotl.jpg",
            "epub":"agatha-christie_the-murder-on-the-links",
            "tags":["fiction", "mystery"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Agatha_Christie",
            "bookWikiLink":"https://en.wikipedia.org/wiki/The_Murder_on_the_Links",
        },
        {
            "id":"13",
            "name":"A Study in Scarlet",
            "author":"Arthur Conan Doyle",
            "cover":"asis.jpg",
            "epub":"arthur-conan-doyle_a-study-in-scarlet",
            "tags":["fiction", "mystery"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Arthur_Conan_Doyle",
            "bookWikiLink":"https://en.wikipedia.org/wiki/A_Study_in_Scarlet",
        },
        {
            "id":"14",
            "name":"The Mysterious Affair at Styles",
            "author":"Agatha Christie",
            "cover":"tmaas.jpg",
            "epub":"agatha-christie_the-mysterious-affair-at-styles",
            "tags":["fiction", "mystery"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Agatha_Christie",
            "bookWikiLink":"https://en.wikipedia.org/wiki/The_Mysterious_Affair_at_Styles",
        },
        {
            "id":"15",
            "name":"The Tragical History of Doctor Faustus",
            "author":"Christopher Marlowe",
            "cover":"tthodf.jpg",
            "epub":"christopher-marlowe_the-tragical-history-of-doctor-faustus",
            "tags":["drama"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Christopher_Marlowe",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Doctor_Faustus_(play)",
        },
        {
            "id":"16",
            "name":"Treasure Island",
            "author":"Robert Louis Stevenson",
            "cover":"ti.jpg",
            "epub":"robert-louis-stevenson_treasure-island",
            "tags":["adventure", "children", "fiction"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Robert_Louis_Stevenson",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Treasure_Island",
        },
        {
            "id":"17",
            "name":"Around the World in Eighty Days",
            "author":"Jules Verne",
            "cover":"atwied.jpg",
            "epub":"jules-verne_around-the-world-in-eighty-days_george-makepeace-towle",
            "tags":["adventure", "fiction"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Jules_Verne",
            "bookWikiLink":"https://en.wikipedia.org/wiki/Around_the_World_in_Eighty_Days",
        },
        {
            "id":"18",
            "name":"The Land That Time Forgot",
            "author":"Edgar Rice Burroughs",
            "cover":"tlttf.jpg",
            "epub":"edgar-rice-burroughs_the-land-that-time-forgot",
            "tags":["adventure", "scifi"],
            "authorWikiLink":"https://en.wikipedia.org/wiki/Edgar_Rice_Burroughs",
            "bookWikiLink":"https://en.wikipedia.org/wiki/The_Land_That_Time_Forgot_(novel)",
        }
    ]
}

const tags = ["all", "scifi", "fiction", "horror", "adventure", "spirituality", "philosophy", "mystery", "drama", "children"]
const ignored = [
    {
        "id":"",
        "name":"",
        "author":"",
        "cover":".jpg",
        "epub":"",
        "tags":[]
    },
    {
            "id":"1",
            "name":"The Three Body Problem",
            "cover":"3bp.jpeg",
            "epub":"three-body-problem",
            "tags":["scifi"]
    },
]